import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

// 1. ADD THIS IMPORT LINE
import Header from '@/components/Header'; // (Assuming your Header.tsx is in a 'components' folder)

const geistSans = Geist({
variable: "--font-geist-sans",
subsets: ["latin"],
});

const geistMono = Geist_Mono({
variable: "--font-geist-mono",
subsets: ["latin"],
});

export const metadata: Metadata = {
title: "Online Examination Portal", // (I'd recommend updating this title too)
description: "Generated by create next app",
};

export default function RootLayout({
children,
}: Readonly<{
children: React.ReactNode;
}>) {
return (
<html lang="en">
<body
className={`${geistSans.variable} ${geistMono.variable} antialiased`}
 >
        {/* 2. ADD YOUR HEADER COMPONENT HERE */}
        <Header />

{children}
</body>
</html>
  );
}